### ISSUE TITLE
Bug: render scaled region: integer argument expected, got float

### ISSUE THREAD

**Issue by will-moore** [ome/omero-figure#453]
Seen on IDR:

```
Traceback (most recent call last):
...

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_figure/views.py", line 203, in render_scaled_region
    canvas = Image.new("RGB", (width, height), (221, 221, 221))

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/PIL/Image.py", line 2698, in new
    return im._new(core.fill(mode, size, color))

TypeError: integer argument expected, got float

<WSGIRequest: GET '/figure/render_scaled_region/9836998/71/0/?c=1%7C3:246$00FF00,2%7C6:133$FF0000&maps=[%7B%22reverse%22:%7B%22enabled%22:false%7D%7D,%7B%22reverse%22:%7B%22enabled%22:false%7D%7D]&region=158,5,1267,787&m=c'>
```

**Comment by will-moore** [comment]
Seen on nightshade just now: 
/figure/render_scaled_region/4486420/0/0/?region=NaN,NaN,7156,7156

```
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_figure/views.py", line 191, in render_scaled_region
    x = int(x * scale)

ValueError: cannot convert float NaN to integer
```

**Comment by will-moore** [comment]
https://www.openmicroscopy.org/qa2/qa/feedback/37359/

If `?region=0,0,1024,1024` is missing, should return 404 instead of Error:

```
Traceback (most recent call last):

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_figure/views.py", line 181, in render_scaled_region
x, y, width, height = [float(r) for r in region.split(',')]

AttributeError: 'NoneType' object has no attribute 'split'
```
