### ISSUE TITLE
DUMMY permissions on save_web_figure

### ISSUE THREAD

**Issue by will-moore** [ome/omero-figure#459]
```
Analyze this line2022-04-08 17:54:31,021 ERROR [ django.request] (proc.05280) log_response():230 Internal Server Error: /figure/save_web_figure/
...
Analyze this lineserverStackTrace = ome.conditions.ApiUsageException: No valid permissions available! DUMMY permissions are not intended for copying. Make sure that you have not passed omero.group=-1 for a save without context
```

**Comment by joshmoore** [comment]
Reported again today on ome-demoserver.

**Comment by will-moore** [comment]
Seen again today on demoserver

```
Internal Server Error: /figure/save_web_figure/

ApiUsageException at /figure/save_web_figure/
exception ::omero::ApiUsageException
{
    serverStackTrace = ome.conditions.ApiUsageException: No valid permissions available! DUMMY permissions are not intended for copying. Make sure that you have not passed omero.group=-1 for a save without context
        at ome.model.internal.Permissions.<init>(Permissions.java:164)
        at ome.security.basic.CurrentDetails.createDetails(CurrentDetails.java:439)

```
