### ISSUE TITLE
Manually run script from JSON

### ISSUE THREAD

**Issue by will-moore** [ome/omero-figure#48]
From @dpwrussell:
I noticed that when I pasted the JSON from figure into the JSON text entry in the script for generating PDFs, then I got this error:

```
Traceback (most recent call last):
  File "./script", line 633, in <module>
    runScript()
  File "./script", line 620, in runScript
    fileAnnotation = create_pdf(conn, scriptParams)
  File "./script", line 547, in create_pdf
    addInfoPage(conn, scriptParams, c, panels_json, figureName)
  File "./script", line 490, in addInfoPage
    c.save()
  File "/usr/local/lib/python2.7/dist-packages/reportlab/pdfgen/canvas.py", line 1215, in save
    self._doc.SaveToFile(self._filename, self)
  File "/usr/local/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 219, in SaveToFile
    data = self.GetPDFData(canvas)
  File "/usr/local/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 244, in GetPDFData
    return self.format()
  File "/usr/local/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 424, in format
    IOf = IO.format(self)
  File "/usr/local/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 869, in format
    fcontent = format(self.content, document, toplevel=1)   # yes this is at top level
  File "/usr/local/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 80, in format
    f = element.format(document)
  File "/usr/local/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 1600, in format
    return D.format(document)
  File "/usr/local/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 676, in format
    L = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]
  File "/usr/local/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 80, in format
    f = element.format(document)
  File "/usr/local/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 1776, in format
    if f is None: raise ValueError("format not resolved %s" % self.name)
ValueError: format not resolved None?show=image-2
```

It works fine when I run export-pdf from figure though.

**Comment by will-moore** [comment]
Moved to trello card https://trello.com/c/v3mSZliO/148-bug-manually-run-script-from-json
