### ISSUE TITLE
Export issue when the lowest resolution is greater than the max plane size

### ISSUE THREAD

**Issue by sbesson** [ome/omero-figure#604]
The issue can be simulated with a synthetic image with the following dimensions

```bash
$ cat test.fake.ini 
sizeX=100000
sizeY=100000
resolutions=5
```

After importing this image into OMERO, creating a figure and trying to export it, the script fails with the following error:

```
Traceback (most recent call last):
  File "./script", line 2562, in <module>
    run_script()
  File "./script", line 2548, in run_script
    file_annotation = export_figure(conn, script_params)
  File "./script", line 2504, in export_figure
    return fig_export.build_figure()
  File "./script", line 980, in build_figure
    self.add_panels_to_page(panels_json, image_ids, page)
  File "./script", line 1988, in add_panels_to_page
    image, pil_img = self.draw_panel(panel, page, i)
  File "./script", line 1809, in draw_panel
    pil_img = self.get_panel_image(image, panel, orig_name)
  File "./script", line 1707, in get_panel_image
    pil_img = self.get_panel_big_image(image, panel)
  File "./script", line 1643, in get_panel_big_image
    pil_img = self.render_big_image_region(image, panel, z, t,
  File "./script", line 1563, in render_big_image_region
    scale, level = self.get_zoom_level_scale(image, region, max_width)
  File "./script", line 1548, in get_zoom_level_scale
    zm_levels[zm] * width * zm_levels[zm] * height > max_plane):
KeyError: 5
```
The logic in
https://github.com/ome/omero-figure/blob/1dfb1389e449594defce3d4ac9f72df3fefb6e89/omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py#L1700-L1704
assumes that a resolution lower than the maximum plane size will be found which is incorrect. Minimally this should be updated  to handle the case where the lowest resolution is greated than 3kx3k in a default configuration.

This raises the question of the how the export script and more generally the application should behave in these scenarios. One approach would be to use tile render calls rather than plane calls but this might be a larger effort. Another option would be to block render calls with an informative error message when the lowest resolution is larger than the maximum plane size  similarly to what was done in https://github.com/ome/omero-figure/pull/560 for maximum projection.

**Comment by knabar** [comment]
I think the issue in the `while` loop is missing parentheses around the `or` term, once `zm < max_level` turns `False` and `max_width` or `max_plane` are still exceeded:

```python
>>> False and True or True
True
>>> False and (True or True)
False
```

The question of what should happen when `max_width` or `max_plane` are exceeded is of course still open anyway.

**Comment by lguerard** [comment]
Hi, 
We're still having this issue with some images. Is there any news regarding this ? 

Can we "just" add a parenthesis to fix this on our server ? Should this be fixed in OMERO.figure then (or OME figure ;) ) ?

**Comment by will-moore** [comment]
@lguerard Does adding the parentheses work for you or do you then get an OOM error?

I'm wondering whether we could avoid an OOM at:

```
jpeg_data = image.renderJpegRegion(z, t, x, y, width, height, level=level)
```

by checking if width and height are "too big" and if so then we render the region by breaking it up into tiles (e.g. 8 by 8) and then calling `renderJpegRegion()` for each tile, and pasting them all together to form the larger region?

Does that sound like it's worth investigating @sbesson

**Comment by michaelmell** [comment]
Dear @will-moore ,

we have tested modifying the figure export script by adding the parentheses around the `or` statement in the while-loop. It fixes the failing export for one of our OMERO figures.

I have asked the user with the problematic figures/data to do some further testing and will report back in case something further comes up. But currently it looks good!

Thanks for your support and kind regards,
Michael

Tagging colleagues: @lguerard

EDIT:

This is the updated while condition for completeness:

```python
        while (zm < max_level and
               (zm_levels[zm] * width > max_width or
               zm_levels[zm] * width * zm_levels[zm] * height > max_plane)):
```
